Added benchmarking infrastructure
mehdi-goli/sycl-blas pull request #7
Opened 2017-06-21 13:56 UTC by theoden8

I've added some benchmarks to measure, compare and keep track of the performance.

2017-07-12 13:53 UTC, Ruyk requested changes
Some comments, seems you have done a lot of work, well done!

2017-07-12 13:53 UTC, Ruyk commented on bench/benchmark.hpp
> +#pragma omp parallel for
Please remove the OpenMP

2017-07-12 13:53 UTC, Ruyk commented on bench/clblas_benchmark.cpp
> +                                      size * sizeof(ScalarT), NULL, NULL);
Please be aware of the different flags for creating buffers: https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/clCreateBuffer.html

2017-07-12 13:53 UTC, Ruyk commented on bench/clblast_benchmark.cpp
> +      ScalarT alpha(2.4367453465);
create a global constant for your random number

2017-07-12 13:53 UTC, Ruyk commented on bench/clblast_benchmark.cpp
> +        clWaitForEvents(5, events);
sizeof(events)

2017-07-12 13:53 UTC, Ruyk commented on bench/clwrap.hpp
> +  cl_command_queue *_queue() { return &command_queue; }
why do you need this one?

2017-07-12 13:53 UTC, Ruyk commented on bench/clwrap.hpp
> +  Context &context;
why a reference?

2017-07-12 13:53 UTC, Ruyk commented on bench/syclblas_benchmark.cpp
> +    UNPACK_PARAM;
Can this be a function instead of a macro?

2017-07-13 16:17 UTC, theoden8 commented on bench/clwrap.hpp
> +  cl_command_queue *_queue() { return &command_queue; }
Clblast wants cl_command_queue * as an argument

2017-07-13 16:18 UTC, theoden8 commented on bench/clblast_benchmark.cpp
> +        clWaitForEvents(5, events);
I am not sure it is a part of the standard. There is an example of how to use sizeof(block), but I have not found an explicit statement.

2017-07-13 16:18 UTC, theoden8 commented on bench/clblast_benchmark.cpp
> +      ScalarT alpha(2.4367453465);
It is type-dependent, only can make a macro out of it.

2017-07-13 16:19 UTC, theoden8 commented on bench/clblas_benchmark.cpp
> +                                      size * sizeof(ScalarT), NULL, NULL);
I would ask for help with understanding which of them are important for the benchmarks.

2017-07-13 16:19 UTC, theoden8 commented on bench/benchmark.hpp
> +#pragma omp parallel for
Done

2017-07-13 16:20 UTC, theoden8 commented on bench/syclblas_benchmark.cpp
> +    UNPACK_PARAM;
Yes, but I wanted to make the same template arguments, return value and parameters which would be defined in benchmarks.hpp.

2017-08-18 23:44 UTC, closed without merging